//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShift.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyShift.Resources.Languages.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon:.
        /// </summary>
        internal static string AfternoonShift {
            get {
                return ResourceManager.GetString("AfternoonShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Off:.
        /// </summary>
        internal static string DayOff {
            get {
                return ResourceManager.GetString("DayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Afternoon.
        /// </summary>
        internal static string FirstAfternoon {
            get {
                return ResourceManager.GetString("FirstAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Day Off.
        /// </summary>
        internal static string FirstDayOff {
            get {
                return ResourceManager.GetString("FirstDayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Morning.
        /// </summary>
        internal static string FirstMorning {
            get {
                return ResourceManager.GetString("FirstMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Night.
        /// </summary>
        internal static string FirstNight {
            get {
                return ResourceManager.GetString("FirstNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Afternoon.
        /// </summary>
        internal static string FourthAfternoon {
            get {
                return ResourceManager.GetString("FourthAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Day Off.
        /// </summary>
        internal static string FourthDayOff {
            get {
                return ResourceManager.GetString("FourthDayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Morning.
        /// </summary>
        internal static string FourthMorning {
            get {
                return ResourceManager.GetString("FourthMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning:.
        /// </summary>
        internal static string MorningShift {
            get {
                return ResourceManager.GetString("MorningShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night:.
        /// </summary>
        internal static string NightShift {
            get {
                return ResourceManager.GetString("NightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Afternoon.
        /// </summary>
        internal static string SecondAfternoon {
            get {
                return ResourceManager.GetString("SecondAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Day Off.
        /// </summary>
        internal static string SecondDayOff {
            get {
                return ResourceManager.GetString("SecondDayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Morning.
        /// </summary>
        internal static string SecondMorning {
            get {
                return ResourceManager.GetString("SecondMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Night.
        /// </summary>
        internal static string SecondNight {
            get {
                return ResourceManager.GetString("SecondNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team View.
        /// </summary>
        internal static string TeamView {
            get {
                return ResourceManager.GetString("TeamView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Afternoon.
        /// </summary>
        internal static string ThirdAfternoon {
            get {
                return ResourceManager.GetString("ThirdAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Day Off.
        /// </summary>
        internal static string ThirdDayOff {
            get {
                return ResourceManager.GetString("ThirdDayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Morning.
        /// </summary>
        internal static string ThirdMorning {
            get {
                return ResourceManager.GetString("ThirdMorning", resourceCulture);
            }
        }
    }
}
